[build]
  base    = "client"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_BASE_URL = "/api"   # le front appellera /api

# Proxy des appels API vers Render
[[redirects]]
  from = "/api/*"
  to = "https://inaturamouche.onrender.com/:splat"
  status = 200
  force = true

# SPA fallback (Vite/React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache long pour assets fingerprintés Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pas de cache sur le HTML
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

# (Optionnel) Sécurité de base côté statique
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
