# netlify.toml — à la racine du dépôt
[build]
  base    = "client"        # on construit depuis /client
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_BASE_URL = "/api" # le front appelle /api (proxy Netlify)

# Proxy des appels API vers Render (supprime CORS côté navigateur)
[[redirects]]
  from = "/api/*"
  to = "https://inaturamouche-api.onrender.com/:splat"
  status = 200
  force = true

# SPA fallback (Vite/React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
