[build]
  base    = "client"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_BASE_URL = "/api"   # le front appellera /api

# Proxy des appels API vers Render
[[redirects]]
  from = "/api/*"
  to = "https://inaturamouche.onrender.com/:splat"
  status = 200
  force = true

# SPA fallback (Vite/React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
