# netlify.toml — Inaturamouche (front sur Netlify, API sur Render)

########################################
# Build du client (Vite) depuis /client
########################################
[build]
  base    = "client"
  command = "npm ci && npm run build"
  publish = "dist"

########################################
# Redirects
########################################

# Proxy API -> Render (utile si tu veux aussi consommer /api en relatif)
[[redirects]]
  from = "/api/*"
  to   = "https://inaturamouche.onrender.com/:splat"
  status = 200
  force  = true

# Exclude assets from SPA fallback
[[redirects]]
  from = "/assets/*"
  to   = "/assets/:splat"
  status = 200

# SPA fallback pour le routage client
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

########################################
# Headers — Cache & Sécurité
########################################

# Cache long et immuable pour les assets fingerprintés de Vite (/assets/*)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pas de cache pour l'HTML (permet les updates immédiates)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

# Service Worker et bundles Workbox : éviter un cache long
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "no-cache"

# Sécurité (CSP élargie pour Google Fonts ET Render en connect-src)
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    # NOTE: on autorise explicitement https://inaturamouche.onrender.com dans connect-src
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.inaturalist.org https://inaturamouche.onrender.com https://static.inaturalist.org https://inaturalist-open-data.s3.amazonaws.com; img-src 'self' data: https: https://static.inaturalist.org https://inaturalist-open-data.s3.amazonaws.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https: data: https://fonts.gstatic.com; script-src 'self'; worker-src 'self' blob:; frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Resource-Policy = "cross-origin"
